### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Zeqiang-Lai** [bit-isp/HSIR#2]
### HSI Board

- [ ] robustness for results structures
  - [ ] it should work without `log.json`
  - [ ] ignore non results subdirectories

- [ ] adjust box size
